### ISSUE TITLE
REINERSCT cyberjack returns general error when using pinpad with OpenSC

### ISSUE THREAD

**Issue by superbly** [OpenSC/OpenSC#1051]
### Expected behaviour

REINERSCT cyberjack card reader should use PINpad to verify pin when using pkcs11 interface C_Login without specifying a pin.

Can be simulated with the src/text/pintest tool.

### Actual behaviour

PIN verifying failed: Generic reader error
 
Problem seems to be in reader-pcsc.c line 222.
rv = priv->gpriv->SCardControl(card, (DWORD) control, sendbuf, dwSendLength,
				  recvbuf, dwRecvLength, &dwRecvLength);

### Steps to reproduce

Mainly follow the steps from https://github.com/OpenSC/OpenSC/wiki/Pinpad-Readers

1. Upload and initialize IsoApplet to JavaCard
2. Run src/test/pintest
3. Don't specify pin in command line. Should use PINpad but results in general error.

Same works with other readers. (gemalto, omnikey)

### Logs

Logs before error:

0x7fe54bf99700 13:51:24.918 [lt-pintest] reader-pcsc.c:1243:pcsc_detect_readers: Found new PC/SC reader 'REINER SCT cyberJack ecom_a (0167624783) 00 00'
0x7fe54bf99700 13:51:24.969 [lt-pintest] reader-pcsc.c:1048:detect_reader_features: Reader supports pinpad PIN verification
0x7fe54bf99700 13:51:24.969 [lt-pintest] reader-pcsc.c:1058:detect_reader_features: Reader supports pinpad PIN modification

Output:
PIN verifying failed: Generic reader error

There are no logs from the error itself.

**Comment by dengert** [comment]
Google for: cyberjack card reader pcsc part 10
This sounds like the reader may not be compliant with PCSC part 10 and may have been fixed in PCSClite.

**Comment by martinpaljak** [comment]
If there is a pinpad issue, the PIN verification block generation parts from the log and actual PIN format should be given.

**Comment by superbly** [comment]
@dengert thank you for the hint. I installed the newest version of pcsc-lite (1.8.21) now but the issue remains. 

@martinpaljak this is the error log section when running pintest -ddd 

0x7fe68028a700 11:00:06.002 [lt-pintest] sec.c:169:sc_pin_cmd: called
0x7fe68028a700 11:00:06.002 [lt-pintest] iso7816.c:1101:iso7816_pin_cmd: Card does not support PIN status queries
0x7fe68028a700 11:00:06.002 [lt-pintest] sec.c:216:sc_pin_cmd: returning with: -1408 (Not supported)
0x7fe68028a700 11:00:06.002 [lt-pintest] card.c:459:sc_unlock: called
0x7fe68028a700 11:00:06.002 [lt-pintest] pkcs15-pin.c:661:sc_pkcs15_get_pin_info: returning with: -1408 (Not supported)
0x7fe68028a700 11:00:06.002 [lt-pintest] pkcs15-pin.c:338:_sc_pkcs15_verify_pin: called
0x7fe68028a700 11:00:06.002 [lt-pintest] pkcs15-pin.c:342:_sc_pkcs15_verify_pin: PIN(type:0; method:1; value(0x23e3d10:0)
0x7fe68028a700 11:00:06.002 [lt-pintest] card.c:407:sc_lock: called
0x7fe68028a700 11:00:06.002 [lt-pintest] card.c:449:sc_lock: returning with: 0 (Success)
0x7fe68028a700 11:00:06.002 [lt-pintest] sec.c:169:sc_pin_cmd: called
0x7fe68028a700 11:00:06.002 [lt-pintest] reader-pcsc.c:1950:pcsc_pin_cmd: called
0x7fe68028a700 11:00:06.002 [lt-pintest] reader-pcsc.c:1993:pcsc_pin_cmd: 
PC/SC v2 pinpad block (40 bytes):
1E 1E 02 10 00 10 04 02 00 00 00 00 00 00 00 15 ................
00 00 00 00 20 00 01 10 00 00 00 00 00 00 00 00 .... ...........
00 00 00 00 00 00 00 00                         ........
0x7fe68028a700 11:00:06.002 [lt-pintest] reader-pcsc.c:212:pcsc_internal_transmit: called
0x7fe68028a700 11:00:06.004 [lt-pintest] reader-pcsc.c:2039:pcsc_pin_cmd: PIN command failed: -1100 (Generic reader error)
0x7fe68028a700 11:00:06.004 [lt-pintest] iso7816.c:1147:iso7816_pin_cmd: APDU transmit failed: -1100 (Generic reader error)
0x7fe68028a700 11:00:06.004 [lt-pintest] sec.c:216:sc_pin_cmd: returning with: -1100 (Generic reader error)
0x7fe68028a700 11:00:06.004 [lt-pintest] pkcs15-pin.c:414:_sc_pkcs15_verify_pin: PIN cmd result -1100
0x7fe68028a700 11:00:06.004 [lt-pintest] card.c:459:sc_unlock: called
0x7fe68028a700 11:00:06.004 [lt-pintest] pkcs15-pin.c:417:_sc_pkcs15_verify_pin: returning with: -1100 (Generic reader error)
0x7fe68028a700 11:00:06.004 [lt-pintest] pkcs15-pin.c:324:sc_pkcs15_verify_pin: returning with: -1100 (Generic reader error)
0x7fe68028a700 11:00:06.004 [lt-pintest] card.c:459:sc_unlock: called
0x7fe68028a700 11:00:06.004 [lt-pintest] reader-pcsc.c:662:pcsc_unlock: called
PIN verifying failed: Generic reader error

**Comment by superbly** [comment]
I don't know if this helps. But when I use the pkcs11-tool with the opensc-pkcs11.so library and I try to login with the pinpad, I don't see any APDU messages sent to the reader in the pcscd log. When I use a proprietary card with it's own pkcs11 library (still using the opnsc pkcs11-tool), I can see the following APDUs sent to the card to verify the pin:

00000003 APDU: 81 34 00 03 03 
00005962 SW: 03 00 01 90 00 
00000003 APDU: 81 34 00 03 03 
00005962 SW: 03 00 01 90 00 
00000003 APDU: 81 34 00 03 03 
00005962 SW: 03 00 01 90 00 
00000003 APDU: 81 34 00 03 03 
00005870 SW: 03 00 01 90 00 
00000003 APDU: 81 34 00 01 03 
00006086 SW: 03 03 01 90 00 
00000002 APDU: 81 34 00 02 03 
00005548 SW: 03 03 00 90 00 
00000003 APDU: 01 CA 01 02 06 
00019593 SW: 7F FF 20 20 0C 0A 90 00 
00000004 APDU: 81 34 00 03 03 
00005855 SW: 03 00 01 90 00 
00000002 APDU: 81 34 00 01 03 
00006109 SW: 03 03 01 90 00 
00000002 APDU: 81 34 00 02 03 
00005511 SW: 03 03 00 90 00

**Comment by frankmorgner** [comment]
I've successfully tested their cyberJack RFID komfort with the PIN pad (contact based cardos card). The reader uses a similar firmware to the ecom reader.

Please check their tool for firmware updates and contact REINER SCT, if the problem persists.

**Comment by superbly** [comment]
I tested with REINER SCT cyberJack and cyberJack go and updated the firmwares of the readers.
The difference what I see when OpenSC makes the call to the driver (SCardControl) the buffer sent looks like this:

len: 40
buffer: 
1e 1e 02 10 00 10 04 02 00 00 
00 00 00 00 00 15 00 00 00 00
20 00 01 10 00 00 00 00 00 00 
00 00 00 00 00 00 00 00 00 00

whereby in the REINER test code the buffer is:
len: 32
buffer: 
00 00 89 47 04 08 04 02 00 00
00 00 00 00 00 0D 00 00 00 00
20 00 80 08 20 FF FF FF FF FF 
FF FF

When I substitute with the buffer which I found in the REINER code, it works.
I check why these buffers are so different.

**Comment by dengert** [comment]
What card driver are you using? To use a pin pad reader, the pkcs15-<card>.c needs to set pin_info structure that include min and max pin lengths and the format of the pin command to be used when using a pin pad reader. It looks liek it assumed a 16 byte pin and other wrong options.

**Comment by superbly** [comment]
Thank you for the hint. 

My setup is:
- Ubuntu 16.04.2 LTS
- libifd-cyberjack6v5 (REINER driver)
- REINER cyberjack reader
- NXP JCOP 2.4.1R3 (card)
- IsoApplet on card

The problem indeed was the max so-pin length configured in the isoApplet.profile. 
I set it to 15 and now it works.
The strange thing is that with other readers (OMNIKEY) it worked also with max pin length of 16.
Is it possible that some readers are not able to handle pins with 16 numbers?

**Comment by superbly** [comment]
**Fix**

Make sure the maximum pin length is smaller than 16 in the profile file of the applet (example isoApplet.profile) when using REINERSCT cyberJack.

**Comment by zdreicom** [comment]
it is for me to but i'm using mac os do you have an idea you to configure on mac os
