### ISSUE TITLE
opensc-notify.exe(from OpenSC 0.20.0-rc2) - Win10( ver1809) - too high processor load

### ISSUE THREAD

**Issue by mti-sk** [OpenSC/OpenSC#1874]
### Problem Description
Too high processor load on win10 enterprise (ver 1809, build 17763.805 ) by opensc-notify.exe without activity. Still, continuous 30%.
My CPU: Intel Core i5 - 5300U 2,3GHz

### Proposed Resolution
I don't know if the opensc-notify process can be disabled in the opensc.conf configuration. That would be temporary help.

### Steps to reproduce
Only install OpenSC-0.20.0-rc2 version.

### Logs
![obrazek](https://user-images.githubusercontent.com/7874262/69713082-31b97300-1104-11ea-8e9c-00cfbe9a92d3.png)

**Comment by frankmorgner** [comment]
Could you send a debug output log OpenSC? Most likely, there is some unhandled error:
https://github.com/OpenSC/OpenSC/blob/ce71b171e2241104761183471acd0f203e4dad5e/src/tools/opensc-notify.c#L82-L90

Please check if the problem persists after attaching a reader (empty or with card).

**Comment by mti-sk** [comment]
Solved in OpenSC-0.20.0 release

**Comment by frankmorgner** [comment]
The issue still persists, see #1903 for a more detailed analysis
