### ISSUE TITLE
PKCS#11 C_Initialize() copies pInitArgs pointer instead of copying the referenced data

### ISSUE THREAD

**Issue by smuehlst** [OpenSC/OpenSC#2170]
### Problem Description

The PKCS#11 `C_Initialize()` function can be called with a pointer to a `CK_C_INITIALIZE_ARGS` structure. The PKCS#11 specification says about this pointer:

http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/pkcs11-base-v2.40-errata01-os-complete.pdf

```
CK_DEFINEDECLARE_FUNCTION(CK_RV, C_Initialize) {
CK_VOID_PTR pInitArgs
);
```
> If pInitArgs is non-NULL_PTR, `C_Initialize` should cast it to a `CK_C_INITIALIZE_ARGS_PTR` and then
dereference the resulting pointer to obtain the `CK_C_INITIALIZE_ARGS` fields `CreateMutex`,
`DestroyMutex`, `LockMutex`, `UnlockMutex`, `flags`, and `pReserved`. 

Note the explicit statement that the pointer must be dereferenced to obtain the values of the fields. It does not say that the storage for the referenced `CK_C_INITIALIZE_ARGS` structure must persist.

But the OpenSC PKCS#11 library only makes a copy of the pointer and dereferences that pointer later when user-supplied locking functions are called:

https://github.com/OpenSC/OpenSC/blob/175c357c37f6a7d27fe01d68d4b10f2d05eb2971/src/pkcs11/pkcs11-global.c#L145

https://github.com/OpenSC/OpenSC/blob/175c357c37f6a7d27fe01d68d4b10f2d05eb2971/src/pkcs11/pkcs11-global.c#L801-L813

So when the `CK_C_INITIALIZE_ARGS` structure is placed on the stack and goes out of scope after the call to `C_Initialize`, a crash will occur because the function pointers to the locking functions are no longer valid when OpenCS calls them via the `global_locking` pointer.

### Proposed Resolution

To be compliant with the PKCS#11 specification `C_Initialize` must copy the `CK_C_INITIALIZE_ARGS` structure passed via the `pInitArgs` pointer. It must not access the structure passed via the `pInitArgs` pointer after `C_Initialize` returns.

### Steps to reproduce

The [test program](https://gist.github.com/smuehlst/f7c6f78f51674abaf964fb1dfdc7f69c) reproduces the issue with the PKCS#11 library from OpenSC-0.21.0 on Windows. 
The crash was reproduced also on Linux and macOS.

### Logs

The program crashes with the following stack trace:

```
0000000000000000() (Unknown Source:0)
opensc-pkcs11.dll!sc_lock_mutex(void * m) Line 168 (c:\git\OpenSC\src\pkcs11\pkcs11-global.c:168)
opensc-pkcs11.dll!sc_ctx_detect_readers(sc_context * ctx) Line 748 (c:\git\OpenSC\src\libopensc\ctx.c:748)
opensc-pkcs11.dll!C_GetSlotList(unsigned char tokenPresent, unsigned long * pSlotList, unsigned long * pulCount) Line 455 (c:\git\OpenSC\src\pkcs11\pkcs11-global.c:455)
opensctest.exe!main(...) Line 108 (c:\Users\Stephan Mühlstrasser\source\repos\opensctest\opensctest.c:108)
opensctest.exe!invoke_main() Line 79 (d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:79)
opensctest.exe!__scrt_common_main_seh() Line 288 (d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
opensctest.exe!__scrt_common_main() Line 331 (d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:331)
opensctest.exe!mainCRTStartup() Line 17 (d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp:17)
kernel32.dll!00007ffd523b7034() (Unknown Source:0)
ntdll.dll!00007ffd5333cec1() (Unknown Source:0)
```

**Comment by dengert** [comment]
Sounds like a real problem.  Do you want to submit a PR?  

Also look at #2067, as this tries to address a problem in the same area. 
Maybe they can be combined.  

Another potential problem, is different threads pass in different  Mutex routines or different flags. Very unlikely as locking would then not work.

**Comment by smuehlst** [comment]
> Sounds like a real problem. Do you want to submit a PR?

Yes, I think I will be able to come up with a fix.

> Also look at #2067, as this tries to address a problem in the same area.
Maybe they can be combined.

I looked at #2067, and the very first sentence contains a wrong assumption:

> C_Initialize may be called by multiple threads.

This is wrong, see below for quotes from the PKCS#11 specification. An application (a single process) must not call `C_Initialize` more than once before it makes a corresponding call to `C_Finalize`.

> Another potential problem, is different threads pass in different Mutex routines or different flags. Very unlikely as locking would then not work.

That is not possible if the PKCS#11 API is used correctly by an application. From the PKCS#11 spec, description of `C_Initialize`:

http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/errata01/os/pkcs11-base-v2.40-errata01-os-complete.html#_Toc441755803

> `C_Initialize` should be the first Cryptoki call made by an application, except for calls to `C_GetFunctionList`. ... Every call to `C_Initialize` should (eventually) be succeeded by a single call to `C_Finalize`.

http://docs.oasis-open.org/pkcs11/pkcs11-ug/v2.40/cn02/pkcs11-ug-v2.40-cn02.html#_Toc406759986

> To Cryptoki, an application consists of a single address space and all the threads of control running in it.  An application becomes a “Cryptoki application” by calling the Cryptoki function `C_Initialize` from one of its threads; after this call is made, the application can call other Cryptoki functions.  When the application has finished using Cryptoki, it calls the Cryptoki function `C_Finalize` and ceases to be a Cryptoki application.

**Comment by smuehlst** [comment]
@dengert I have now a fix ready, see https://github.com/smuehlst/OpenSC/commit/0e219858fa6d29ab8f4da35645b7d05e1c716a2e.

I tested with the test program that I referenced from above that the crash is fixed. Before I submit a pull request, do I have to include any additional test code in the pull request? Note that on the machine at home where I developed this fix I have no possibility to do any actual testing with the PKCS#11 module.

**Comment by dengert** [comment]
I have been working on something similar on top of #2067  https://github.com/dengert/OpenSC/tree/C_Initialize-locking the last 2 commits. But it is not working as expected. There are a lot of #ifdefs for OS and  whatcompiler. 

When anyone submits a PR, it is run through a number of  tests, so is a way to test your PR on Windows, MacOS and Linux with a number of different compilers. So submit you changes and see if they work.

#2067 has some changes to pkcs11-tool.c to do some primitive tests. It added --test-threads. If you have a better test thae would be good too.

**Comment by Jakuje** [comment]
@smuehlst I see this was yet not fixed nor the PR was submitted from your changes. Can you submit your changes as a PR here? I think this would be worth fixing in OpenSC 0.22.0 due very soon.

**Comment by smuehlst** [comment]
@Jakuje Sorry, I completely forgot about this.
Created pull request #2350.
