### ISSUE TITLE
Feitian ePass3000 pkcs15-init --create-pkcs15 fail with `EF offset too large`

### ISSUE THREAD

**Issue by sztsian** [OpenSC/OpenSC#2515]
### Problem Description
Feitian ePass3000 init fail with

Failed to create PKCS #15 meta structure: EF offset too large

System: Fedora 35 x86_64
self compiled openct against https://github.com/OpenSC/openct/commit/a4f3fcb91dcd78274dffb1b934e4a8c55dbb91a4
self compiled opensc with config `./configure --enable-openct --disable-pcsc --prefix=/usr` against commit https://github.com/OpenSC/OpenSC/commit/6a7be63e38783b6086ced7950ed834bce46f3657

### Proposed Resolution
I don't know. I'm just an end user.

### Steps to reproduce
$ pkcs15-init -E
Using reader with a card: FT SCR2000A
$ pkcs15-init --create-pkcs15 --profile pkcs15+onepin --label “epass3000” 
Using reader with a card: FT SCR2000A
New User PIN.
Please enter User PIN: 
Please type again to verify: 
Unblock Code for New User PIN (Optional - press return for no PIN).
Please enter User unblocking PIN (PUK): 
Please type again to verify: 
Failed to create PKCS #15 meta structure: EF offset too large

### Logs

[opensc-debug.txt](https://github.com/OpenSC/OpenSC/files/8141976/opensc-debug.txt)

**Comment by sztsian** [comment]
@FeitianSmartcardReader

**Comment by sztsian** [comment]
Note, I don't have access to Feitian proprietary driver for Linux as the URL I've been pointed to is now 404
http://entersafe.com/download/ifd-eps3k-linux-x86-64-080917.tar.gz

**Comment by dengert** [comment]
Problem appears to be "Security status not satisfied".

In line 2429 "card.c:733:sc_update_binary: called; 128 bytes at index 0" an attempt to write to the card ends in line 2466 card returns `6982` "Security status not satisfied" which means the user or SO pin needs to be verified before the operation can be done. 

The error is converted into "card.c:766:sc_update_binary: returning with: -1415 (EF offset too large)"

**Comment by dengert** [comment]
Also see: https://github.com/OpenSC/OpenSC/issues/2018#issuecomment-621100431
and use of --use-default-transport-key

**Comment by sztsian** [comment]
Thanks @dengert. Unfortunately, adding `--use-default-transport-key` did not solve my problem. I still get the same failure.
```
$ pkcs15-init -E
Using reader with a card: FT SCR2000A
$ pkcs15-init --create-pkcs15 --profile pkcs15+onepin --use-default-transport-key --pin 12345678 --puk entersafe --label "epass3000"
Using reader with a card: FT SCR2000A
Failed to create PKCS #15 meta structure: EF offset too large
```
[opensc-debug-pkcs15-onepin.txt](https://github.com/OpenSC/OpenSC/files/8148790/opensc-debug-pkcs15-onepin.txt)

One thing I noticed, I am using ePass**3000** instead of ePass2003. On the wiki page for [ePass 3000](https://github.com/OpenSC/OpenSC/wiki/Feitian-ePass3000) it mentions the driver as `entersafe`. So I also tried to use entersafe as profile, but tails too.
```
$ pkcs15-init -E
Using reader with a card: FT SCR2000A
$ pkcs15-init --create-pkcs15 --profile entersafe --use-default-transport-key --pin 12345678 --puk entersafe --label "epass3000"
Using reader with a card: FT SCR2000A
Couldn't bind to the card: Syntax error
```
[opensc-debug-entersafe.txt](https://github.com/OpenSC/OpenSC/files/8148803/opensc-debug-entersafe.txt)

**Comment by dengert** [comment]
Look at  `/usr/share/opensc/entersafe.profile` to see what is the syntax error. 
https://github.com/OpenSC/OpenSC/blob/master/src/pkcs15init/profile.c#L1298
(Unfortunately it does not listed the line number.)

**Comment by sztsian** [comment]
Sorry that I realized the above command is not right. But I'm getting closer.

I find I can compile opensc-0.16.0 in my system (but no any versions between that and 0.22.0) so I tried with 0.16.0 with openct support. I get the card working with commands

```
$ pkcs15-init -E
Using reader with a card: FT SCR2000A
$ pkcs15-init --create-pkcs15 --profile pkcs15+entersafe --use-default-transport-key --pin 12345678 --puk entersafe --label "3000"
Using reader with a card: FT SCR2000A
New User PIN.
Please enter User PIN: 
Please type again to verify: 
Unblock Code for New User PIN (Optional - press return for no PIN).
Please enter User unblocking PIN (PUK): 
Please type again to verify: 
$ 
```
Attached is the log with 0.16.0

[opensc-debug-0.16.0.txt](https://github.com/OpenSC/OpenSC/files/8154027/opensc-debug-0.16.0.txt)

However, with the same commands, it doesn't work on 0.22.0

```
$ pkcs15-init -E
Using reader with a card: FT SCR2000A
$ pkcs15-init --create-pkcs15 --profile pkcs15+entersafe --use-default-transport-key --pin 12345678 --puk entersafe --label "3000"
Using reader with a card: FT SCR2000A
New User PIN.
Please enter User PIN: 
Please type again to verify: 
Sorry, the two pins did not match. Please try again.
Please enter User PIN: 
Please type again to verify: 
Unblock Code for New User PIN (Optional - press return for no PIN).
Please enter User unblocking PIN (PUK): 
Please type again to verify: 
Failed to create PKCS #15 meta structure: EF offset too large
```
Attached is the log

[opensc-debug-0.22.0.txt](https://github.com/OpenSC/OpenSC/files/8154036/opensc-debug-0.22.0.txt)

I manually read the end of both files, and find something interesting.

In the log of 0.16.0 (the working one),  starting line 3727, `00 A4 00 00 02 49 46 E0 .....IF.`, it got incoming APDU `6F 07 82 01 00 80 02 00 80 90 00`. After this response, IMO it called the workflow of authenticating, and the next outgoing APDU is on line 3777 `00 20 00 01 10 31 32 33 34 35 36 37 38 00 00 00 . ...12345678...`, which is the PIN.

However, in the log of 0.22.0 (the broken one), starting with line 2790 `00 A4 00 00 02 49 46 E0 .....IF.`, it's the same outgoing APDU. And the response is the same on line 2794. **But**, the following outgoing APDU is strange - it's a long block starting by line 2819, `00 D6 00 00 80 01 06 70 6B 63 73 31 35 02 09 65 .......pkcs15..e` which isn't the PIN, and even not fully the PUK. And it repeated twice before getting `69 82` response.

So I think this is where everything start to fail.

However, I don't have much knowledge on how smart card should work, so I don't fully understand what's expected here.

**Comment by dengert** [comment]
Although d06f23e89 does not log pin commands to avoid exposing the PIN unless debug >=  SC_LOG_DEBUG_PIN

**Comment by dengert** [comment]
Sorry, I het the wrong button.

**Comment by dengert** [comment]
SC_LOG_DEBUG_PIN is level 8.  But even without this level the 0.16.0 log show sc_pin_cmd being called 8 times, but the 0.22.0 log shows it is called 0 times.  So compare the  `entersafe.profile` from the 2 versions  which gets installed  `<prefix>/share/opensc` like `/usr/local/share/opensc` to why `pkcs15-init` may not be ge doing a verify of a PIN.

**Comment by sztsian** [comment]
The `entersafe.profile` are exactly the same for the two versions.
```
$ diff /usr/share/opensc/entersafe.profile Desktop/entersafe.profile.22
$ echo $?
0
```
[entersafe.profile.txt](https://github.com/OpenSC/OpenSC/files/8154679/entersafe.profile.txt)

**Comment by dengert** [comment]
This problem maybe similar to the epass2003 problem:  https://github.com/OpenSC/OpenSC/issues/2397 which was fixed by 
 https://github.com/OpenSC/OpenSC/commit/bb096caed  The problem is listed here: https://github.com/OpenSC/OpenSC/issues/2397#issuecomment-913700870

I was able to test the fix as I have a epass2003 but do not have a epass3000. 

Some other questions about your environment:
- What OS?
- Why are you using openct, rather then pcscd?
- Are you running both the 0.16.0 and 0.22.0 on the same machine?
- Are you using the same token in both tests?
- How did you build the two versions?
If you are running two versions on the same machine it is strange that both logs show they are using `/usr/share/opensc`

**Comment by FeitianSmartcardReader** [comment]
@sztsian would you please send mail to leon@ftsafe.com, he is the right person of PKI part, thanks
And BTW, epass3000 is very old version, we suggest you switch to epass2003

**Comment by sztsian** [comment]
> This problem maybe similar to the epass2003 problem: #2397 which was fixed by [bb096caed](https://github.com/OpenSC/OpenSC/commit/bb096caed) The problem is listed here: [#2397 (comment)](https://github.com/OpenSC/OpenSC/issues/2397#issuecomment-913700870)
> 
> I was able to test the fix as I have a epass2003 but do not have a epass3000.
> 

Thanks for the tips. I actually have the patch applied to the 0.22.0 I compile. I guess it's still happening because ePass 3000 and ePass 2003 share different code path. IIUC, ePass 3000 uses [card-entersafe.c](https://github.com/OpenSC/OpenSC/blob/master/src/libopensc/card-entersafe.c) while the fix you mentioned above is on `card-epass2003.c`.

> Some other questions about your environment:
> 
>     * What OS?

Linux. It's Fedora 35 x86_64

>     * Why are you using openct, rather then pcscd?

Although ePass 300 is listed in the [smartcard_list](https://src.fedoraproject.org/rpms/pcsc-tools/blob/f35/f/smartcard_list.txt#_332), pcsc_scan cannot detect ePass 3000 in my system. So I have to try openct.
```
$ lsusb | grep 3000
Bus 003 Device 006: ID 096e:0401 Feitian Technologies, Inc. ePass3000
$ sudo pcsc_scan 
Using reader plug'n play mechanism
Scanning present readers...
Waiting for the first reader... |
```

>     * Are you running both the 0.16.0 and 0.22.0 on the same machine?

Yes.

>     * Are you using the same token in both tests?

Yes.

>     * How did you build the two versions?

I modified the SPEC file of compiling opensc RPM, compiled RPM for 0.16.0 and 0.22.0 with openct support, and then I install the RPM I need to test onto my system. In this way, I can guarantee everything I use is from the expected version.

The configuration for 0.22.0 is
```
%configure  --disable-static --enable-openct --disable-autostart-items --disable-notify --disable-assert --disable-pcsc
```

And for 0.16.0 is

```
%configure  --disable-static --enable-openct --disable-ctapi --disable-pcsc --disable-assert
```
I've shared both of the full RPM SPEC [here](https://gist.github.com/sztsian/cfa8e34ee898bbdb2e18edf29520e012)

>       If you are running two versions on the same machine it is strange that both logs show they are using `/usr/share/opensc`

To avoid polluting the result, each time I install the RPM package I built so the other one get removed by dnf. That's why both logs shows the same dir.

HTH.

**Comment by sztsian** [comment]
> @sztsian would you please send mail to [leon@ftsafe.com](mailto:leon@ftsafe.com), he is the right person of PKI part, thanks And BTW, epass3000 is very old version, we suggest you switch to epass2003

Thanks for the info. I'll send Leon emails shortly.
Meanwhile, I've purchased a ePass 2003 after I first failure with ePass 3000 and I'm also evaluating my use scenario with it now.

**Comment by dengert** [comment]
Thanks. The swapping the RMPs explains a lot. While writing this note, I see you have switched to testing an epass2003. 

What I was implying with "This problem maybe similar to the epass2003 problem: https://github.com/OpenSC/OpenSC/issues/2397" is that the epass3000 may have the same problem, and equivalent code may be needed in `card-entersafe.c`.

OpenSC has many older card drivers and no way to know if these are being used in production environments or just by hobbyists. In many cases, OpenSC relies on users with a card for testing and fixes. Only because Gooze sent me an epass2003 in 2014 was I able to create a fix for https://github.com/OpenSC/OpenSC/issues/2397

If you are willing to develop and submit changes to OpenSC,  I would suggest that you use "git" and  clone the OpenSC repository. Then build to use `/usr/local` (the default) or use the `--prefix` option of configure.

**Comment by sztsian** [comment]
> What I was implying with "This problem maybe similar to the epass2003 problem: #2397" is that the epass3000 may have the same problem, and equivalent code may be needed in `card-entersafe.c`.

Ah, thanks. Now I get your point.

> OpenSC has many older card drivers and no way to know if these are being used in production environments or just by hobbyists. In many cases, OpenSC relies on users with a card for testing and fixes. Only because Gooze sent me an epass2003 in 2014 was I able to create a fix for #2397

Actually I'm also not using it for business purpose. Recently I am looking into something for signing our RPM packages so I start to try different tokens that is available to me. The only reason I choose ePass 3000 is that it's the most easily available for me and it's said to be supported in my early research. As Feitian mentioned above, ePass 2003 is newer, that is also an option for me. And I've already get that working. So I don't have strong requests regarding this issue now rather than try to help figuring out the cause so that others can know what to expect.

> If you are willing to develop and submit changes to OpenSC, I would suggest that you use "git" and clone the OpenSC repository. Then build to use `/usr/local` (the default) or use the `--prefix` option of configure.

Sure, if I can figure out something to make it work, I'll definitely contribute back.

**Comment by lwinch2006** [comment]
I'm facing the same "EF offset too large" error when trying to create PKCS15 structure. 
Hardware: Macbook with Apple Silicon
OS: MacOS Monterey
OpenSC version: OpenSC-0.22.0-rc1-74-gc902e199, rev: c902e199, commit-time: 2021-08-10 11:09:03 +0200

Cannot run FIX_TOOL that is for Linux.

Error log
```
P:2417; T:0x4370777472 01:55:44.947 [pkcs15-init] card-epass2003.c:192:epass2003_check_sw: Security status not satisfied
P:2417; T:0x4370777472 01:55:44.947 [pkcs15-init] iso7816.c:318:iso7816_update_binary: Card returned error: -1211 (Security status not satisfied)
P:2417; T:0x4370777472 01:55:44.947 [pkcs15-init] card.c:523:sc_unlock: called
P:2417; T:0x4370777472 01:55:44.947 [pkcs15-init] card.c:766:sc_update_binary: returning with: -1415 (EF offset too large)
P:2417; T:0x4370777472 01:55:44.947 [pkcs15-init] pkcs15-lib.c:4043:sc_pkcs15init_update_file: returning with: -1415 (EF offset too large)
P:2417; T:0x4370777472 01:55:44.947 [pkcs15-init] pkcs15-lib.c:928:sc_pkcs15init_add_app: returning with: -1415 (EF offset too large)
```

Would be very appreciated for any hints/help how to overcome problem?

**Comment by FeitianSmartcardReader** [comment]
will let our team to take a look. keep update in these days

**Comment by lwinch2006** [comment]
@FeitianSmartcardReader 
yes this is ePass2003 token from 2015, e.g. 7 years old
I will post PID later today when to macen.

**Comment by lwinch2006** [comment]
@FeitianSmartcardReader
Here is output of command `system_profiler SPUSBDataType`

```
    USB 3.1 Bus:

      Host Controller Driver: AppleT6000USBXHCI

        USB Token:

          Product ID: 0x0807
          Vendor ID: 0x096e
          Version: 1.10
          Speed: Up to 12 Mb/s
          Manufacturer: FS
          Location ID: 0x02100000 / 1
          Current Available (mA): 500
          Current Required (mA): 100
          Extra Operating Current (mA): 0
```

**Comment by FeitianSmartcardReader** [comment]
oK will forward to our team to take a look, keep update.

**Comment by FeitianSmartcardReader** [comment]
The fix tool was made for linux only, not for macOS, is that possible switch to linux? and our team is working on check opensc source code, we remember added latest code to avoid such issue.
let me know your opensc version, thanks

**Comment by lwinch2006** [comment]
@FeitianSmartcardReader
OpenSC version mentioned above in original message, e.g.
`OpenSC version: OpenSC-0.22.0-rc1-74-gc902e199, rev: c902e19, commit-time: 2021-08-10 11:09:03 +0200`

Unfortunately linux is not easy available without searching for some virtual image maybe.
But I checked same OpenSC commands on old work PC with Windows and it gives the same "EF offset too large" result.
OpenSC version is the same latest installed there.

**Comment by FeitianSmartcardReader** [comment]
noted, already share to our team, waiting their replay, we will keep you update, thanks

**Comment by lwinch2006** [comment]
Tried now "Format Tool for ePass2003" for windows that you have. It failed with code rv=0x00000030

**Comment by lwinch2006** [comment]
@FeitianSmartcardReader
I have some good news. 
I downgraded OpenSC to 0.20 version, e.g. `OpenSC-0.20.0, rev: 45e2905, commit-time: 2019-12-29 13:42:06 +0100`
And it worked flawlessly.
So here something changed in codebase when 0.22 version was released and that broken functionality.

**Comment by lwinch2006** [comment]
But I also have some bad news
command `pkcs15-init -E` does not work in OpenSC 0.20 and gives "Failed to erase card: Security status not satisfied"

**Comment by lwinch2006** [comment]
Some test results for commands

Works in 0.22 but not in 0.20
```
pkcs15-init -E 
```

Works in 0.20 but not in 0.22
```
pkcs15-init --create-pkcs15 --profile pkcs15+onepin --use-default-transport-key
```

Does not work neither in 0.20 nor 0.22
```
pkcs15-init --create-pkcs15 --profile pkcs15+default --use-default-transport-key 
```
Even if I see default profile in `epass2003.profile` file. So its not possible to take in use SO PIN and PUK

**Comment by lwinch2006** [comment]
Update:
With OpenSC 0.21 (previous version) both commands `pkcs15-init -E` and `pkcs15-init --create-pkcs15 --profile pkcs15+onepin` works

Initialising of pkcs15 structure with default options (incl SO PIN and PUK) not working anywhere. Checked down to 0.16 version.

**Comment by popovec** [comment]
I cannot verify the original problem with ePass3000, but currently ePass2003 works:

OpenSC from GIT (a6eecaa30fc0323967bbd4d82093a45c7ef2d422), 
`````
$ opensc-tool -i
OpenSC 0.23.0-rc2 [gcc  10.2.1 20210110]
Enabled features: locking zlib readline openssl pcsc(libpcsclite.so.1)
`````
Device:  (from lsusb -v)
  idVendor           0x096e Feitian Technologies, Inc.
  idProduct          0x0807 ePass2003

`````
$ pkcs15-init --create-pkcs15 --profile pkcs15+onepin --use-default-transport-key
Using reader with a card: Feitian ePass2003 00 00
New User PIN.
Please enter User PIN: 
Please type again to verify: 
Unblock Code for New User PIN (Optional - press return for no PIN).
Please enter User unblocking PIN (PUK): 
Please type again to verify: 
$ pkcs15-tool -D
Using reader with a card: Feitian ePass2003 00 00
PKCS#15 Card [OpenSC Card]:
        Version        : 0
        Serial number  : 3307011617051201
        Manufacturer ID: EnterSafe
        Last update    : 20221117091037Z
        Flags          : EID compliant


PIN [User PIN]
        Object Flags   : [0x03], private, modifiable
        ID             : 01
        Flags          : [0x32], local, initialized, needs-padding
        Length         : min_len:4, max_len:16, stored_len:16
        Pad char       : 0x00
        Reference      : 1 (0x01)
        Type           : ascii-numeric
        Path           : 3f005015

$ pkcs15-init -E
Using reader with a card: Feitian ePass2003 00 00
$
`````

**Comment by softboy99** [comment]
> Note, I don't have access to Feitian proprietary driver for Linux as the URL I've been pointed to is now 404 http://entersafe.com/download/ifd-eps3k-linux-x86-64-080917.tar.gz

hi,
Is there anyone can share the ifd-eps3k-linux-x86-64-080917.tar.gz? we have 2 ukeys and need this.

**Comment by softboy99** [comment]
@sztsian ，could you please kindly share the driver?
