### ISSUE TITLE
Pkcs11 not finding private key with Italian ID card

### ISSUE THREAD

**Issue by wtmann** [OpenSC/OpenSC#521]
I've been trying to sign a document with the Italian ID card in Java and when I use the Signature object to sign I keep getting the CKR_FUNCTION_NOT_SUPPORTED exception. So I tried to sign using the pkcs11-tool and after inserting the PIN code I get "error: Private key not found". So I re-ran the command with the debug level set to 5 and noticed this oddity:

0x7f9008500740 10:03:14.990 [opensc-pkcs11] pkcs11-object.c:364:C_FindObjectsInit: Object with handle 0x1503320
0x7f9008500740 10:03:14.990 [opensc-pkcs11] pkcs11-object.c:390:C_FindObjectsInit: Object 1/22033184: **Attribute 0x0 matches.**
0x7f9008500740 10:03:14.990 [opensc-pkcs11] pkcs11-object.c:383:C_FindObjectsInit: Object 1/22033184: **Attribute 0x102 does NOT match.**

It seems to be find both a match and a not match on the same handle which is then considered a non-match so it's not finding anything. How could this be?

Thanks.

**Comment by frankmorgner** [comment]
please give a more detailed log. may be related to #393

**Comment by wtmann** [comment]
Thanks for the reply. I was specifying an ID in the command to sign and it was causing this. However, I still get the CKR_FUNCTION_NOT_SUPPORTED exception when signing. The pkcs15-tool lists my private key as:

Private RSA Key [CNS0]
	Object Flags   : [0x1], private
	Usage          : [0x224], sign, unwrap, nonRepudiation
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	ModLength      : 1024
	Key ref        : 49 (0x31)
	Native         : yes
	Auth ID        : 31
	ID             : 31

From the log the signInit and signUpdate calls work as expected. The signFinal is giving a "raw encryption not supported error". I've attached the logs from the command: 

pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -t -l --pin 12345678

Hope this helps in diagnosing this problem. Thanks.

output.log - https://drive.google.com/file/d/0B_lWKDdIYuQTLTBEM3h2Q1REbVE/view?usp=sharing
debug.log - https://drive.google.com/file/d/0B_lWKDdIYuQTQUUzNUNXWlJDTzA/view?usp=sharing

**Comment by dengert** [comment]
The debug log says this is OpenSC 0.13.0, 04.12.2012.
There have been a lot of changes sine then, including CNS card changes.

Can you try running with at least 0.15.0, or better still nightly builds or build the source.

See:
  https://github.com/OpenSC/OpenSC/wiki



On 8/12/2015 4:16 AM, wtmann wrote:
> Thanks for the reply. I was specifying an ID in the command to sign and it was causing this. However, I still get the CKR_FUNCTION_NOT_SUPPORTED exception when signing. The pkcs15-tool lists my
> private key as:
>
> Private RSA Key [CNS0]
> Object Flags : [0x1], private
> Usage : [0x224], sign, unwrap, nonRepudiation
> Access Flags : [0x1D], sensitive, alwaysSensitive, neverExtract, local
> ModLength : 1024
> Key ref : 49 (0x31)
> Native : yes
> Auth ID : 31
> ID : 31
>
>  From the log the signInit and signUpdate calls work as expected. The signFinal is giving a "raw encryption not supported error". I've attached the logs from the command:
>
> pkcs11-tool --module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -t -l --pin 12345678
>
> Hope this helps in diagnosing this problem. Thanks.
>
> output.log - https://drive.google.com/file/d/0B_lWKDdIYuQTLTBEM3h2Q1REbVE/view?usp=sharing
> debug.log - https://drive.google.com/file/d/0B_lWKDdIYuQTQUUzNUNXWlJDTzA/view?usp=sharing
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/521#issuecomment-130231337>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by wtmann** [comment]
Hi,

I built the 0.15.0 version from the source but I still get the same error. So the error is happening in the padding.c file it seems so I'm guessing that since the card uses RSA for signing all of the padding stuff is coming into play. However while reading the functional specs of the card it says that for the SM_ENC and the SM_SIG functions padding isn't applicable using RSA whereas with DES/3DES it is. Is that relevant to what's happening here?

**Comment by dengert** [comment]
Do you have a URL to the specifications?

The SM_ Is Secure Messaging. where the encryption is symmetric, i.e. 3DES. (Hope it does not use single DES)
Signatures with RSA use padding. The question is if the padding is done on the card or in software.

Do you have the debug trace using 0.15.0?


On 8/12/2015 4:46 PM, wtmann wrote:
> Hi,
>
> I built the 0.15.0 version from the source but I still get the same error. So the error is happening in the padding.c file it seems so I'm guessing that since the card uses RSA for signing all of the
> padding stuff is coming into play. However while reading the functional specs of the card it says that for the SM_ENC and the SM_SIG functions padding isn't applicable using RSA whereas with DES/3DES
> it is. Is that relevant to what's happening here?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/521#issuecomment-130458020>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by wtmann** [comment]
I'm including a link to the functional specs (PDF) and to the log with 0.15.0. The pkcs15-tool gives a little bit more information on the private key now, it's as follows:

Private RSA Key [CNS0]
	Object Flags   : [0x1], private
	Usage          : [0x224], sign, unwrap, nonRepudiation
	Access Flags   : [0x1D], sensitive, alwaysSensitive, neverExtract, local
	ModLength      : 1024
	Key ref        : 49 (0x31)
	Native         : yes
	Auth ID        : 31
	ID             : 31
	MD:guid        : {872b288f-17db-5188-7118-5b107edeb178}
	  :cmap flags  : 0x0
	  :sign        : 0
	  :key-exchange: 0

Here are the links:

CIE - Functional Specs - https://drive.google.com/file/d/0B_lWKDdIYuQTeHZyTk9SNEhnMmM/view?usp=sharing
Log 0.15.0 - https://drive.google.com/file/d/0B_lWKDdIYuQTMlE5SnlEQ1FSbk0/view?usp=sharing

I hope this helps. And thanks!

**Comment by dengert** [comment]
In the debug log, line 2567: 
0x7f6b95419740 08:33:17.100 [opensc-pkcs11] pkcs15-sec.c:395:sc_pkcs15_compute_signature: supported algorithm flags 0xC0001FE2, private key usage 0x224
and line 2574:
0x7f6b95419740 08:33:17.100 [opensc-pkcs11] padding.c:308:sc_get_encoding_flags: raw encryption is not supported: -1408 (Not supported)

**Comment by dengert** [comment]
I would venture to say that the  pkcs15-itacns.c lines 790-805 is in the wrong module.
The flags should be sent in the card-cardos.c Waiting till the pkcs15 module is too late and may be the problem.

**Comment by dengert** [comment]
This may be all wrong, but can you try this patch. It tries to set the flags in the correct location. 
This is assuming that the card can not do RAW RSA, but can do padding. It is not clear from the specs if the card can do RAW RSA or not. If it can then the fix may be to just remove the code in pkcs15-iatcns.c

https://github.com/dengert/OpenSC/commit/26d519aeb1a1131443dc648b2d67739577a13c79

Output from pkcs11-tool -M with the old code, the 0.15.0 and the modified code would be helpful.

The flags set in card-cardos.c say what the card can do on the card. The -M options show
what the PKCS#11 the combination of what can be done in software and hardware. OpenSC tries to do as much as possible on the card, but hashing is usually done in the lib.

**Comment by dengert** [comment]
@puccia  is listed as the author of a number of these Italian CNS modules. 

In all the traces, the ATR of your card is 3b:e9:00:ff:c1:10:31:fe:55:00:64:05:00:c8:02:31:80:00:47
This is mapped to card->type=1007, SC_CARD_TYPE_CARDOS_CIE_V1, /* Italian CIE (eID) v1 */
by the card-cardos.c card driver module. And it says the specifications are from:
http://www.cnipa.gov.it/html/docs/CNS%20Functional%20Specification%201.1.5_11012010.pdf
But I can not find this. 

There is also a card-itacns.c, that can define a card-type=SC_CARD_TYPE_ITACNS_CIE_V2
but it was never called,  because the card-cardos.c claimed the match first.

The specifications you sent were for CIE - Functional Specification v2_1_0.pdf
And you talked about "new" cards. 

The PKCS#15 emulation module pkcs15-itacns.c was also selected, and does some tests for SC_CARD_TYPE_CARDOS_CIE_V1 set from the card-cardos.c. (This is unusual as the card-XXX.c
and pkcs15-XXX.c usually are written as a pair, but the comments imply that card-cardos.c and pkcs15-iatcns.c will work together.) 

pkcs15-iatcns.c for the SC_CARD_TYPE_CARDOS_CIE_V1 turns off RAW RSA. But the V2.1 specifications you sent say the cards should support RSA_PURE, which OpenSC and PKCS#11 refer to as RAW RSA. 

You also said the card worked with OpenSC 0.13.0, but none of the traces showed it doing a signature operation.

So it could be that some code was added between 0.13.0 and 0.15.0 that broke something.

It could also be that your card does meet V2.1 specifications, and the card-iatcns.c should have been called before card-cardos.c, so the card is misidentified by OpenSC, if both the V1 and V2 cards have the same ATR. 
 



One way to test this is to change the order ctx.c _sc_driver_entry internal_card_drivers[]
or modify the opensc.conf to only call selected drivers. 

To fix this issue needs a developer that has one or more of these cardos and/or itacns cards. 
I have neither. 







 




The pkcs15-itacns.c is selected for the pkcs#15 routines. 
   http://www.servizidemografici.interno.it/sitoCNSD/documentazioneRicerca.do?metodo=contenutoDocumento&servizio=documentazione&ID_DOCUMENTO=1043

**Comment by puccia** [comment]
I wholeheartedly endorse @dengert's idea of trying to disable card-cardos and see what happens with card-itacns.

I have never tested a CIE card, but I believe that someone did in the past. (Sorry, I have not dealt with this project for a long time and I can't remember the details off the top of my head.)

Hoever, @wtmann, there is a caveat: the first (and usually only) certificate on the card is only meant to be used for authentication, not for document signature operations.

**Comment by wtmann** [comment]
@dengert  The functional specs listed in the source code are not for the ID cards but the CNS cards: the Italian law states that the two are the same but in reality that's not true. None of the digital signature software that I've tried recognize the ID card whereas the CNS cards are recognized. Furthermore, the owners of the ID card cannot legally possess a CNS also (but in reality I have two CNSs and the ID card).

@puccia  The CIE card was also meant for signing documents also. In fact, the certificate has two basic usages: digitalSignature and nonRepudiation. That's why the owners of the CIE can't legally have a CNS also. The extended usage is for authentication.

Having said that, I finally have a working example. What I did was strip the ATR from card-cardos and basically copied and modified the card-itacns and pkcs15-itacns files making a card-itacie and pkcs15-itacie. I'm really not practiced in C and a lot of stuff I just don't get anymore (pointers, pointer to pointers, ecc.) and I haven't really studied the whole opensc framework but what I've done has given me a working card. This is with version 0.13.0 because from version 0.14.0 on the pkcs11 libraries no longer work with Java and that's what I needed it for (see my issue #523). Some things aren't working yet (like the manufacturer) but I need more time and an environment where I can debug the code.

I'm attaching links to the output and log from the pkcs11-tool's test command and the output from my Java test program that uses opensc to get information from the card. There's still some work to do but at least now I know it's doable.

Output from the 'pkcs11-tool --module /usr/lib/opensc-pkcs11.so -l -t' command:
https://drive.google.com/file/d/0B_lWKDdIYuQTaURxTHFjd2NmclU/view?usp=sharing

Log from the above command:
https://drive.google.com/file/d/0B_lWKDdIYuQTbDREZmxtSkxSQ1U/view?usp=sharing

Output from my Java test program:
https://drive.google.com/file/d/0B_lWKDdIYuQTLXpqMzJnQ1dEbGM/view?usp=sharing

**Comment by puccia** [comment]
@wtmann: glad it works! If I understand correctly what you have done, then modifying the opensc.conf file to exclude the cardos driver would have brought the same result.

As far as the CNS vs. CIE issue goes, your claim is incorrect; it is not possible to issue a CNS to a CIE holder, but the CIE holder can keep them. And I think that they won't enforce this rule when they release updated tax ID + health cards with an integrated CNS.

However, I think that it cannot be the rationale behind it. Only the signatures matching the certificates issued by the CA's listed in the official TSL (printout at https://applicazioni.cnipa.gov.it/TSL/IT_TSL_HR.pdf) are strong, legally binding signatures. A signature made with the private key matching the authentication certificate, as far as I can tell, will not be recognised as a valid digital signature by any of the standard signature validation tools in use in Italy, because it isn't.

This is a bit off-topic here, so we continue this discussion privately or elsewhere if you want.

**Comment by wtmann** [comment]
Unfortunately I tried assigning the itacns directly to the ATR in the opensc.conf file; that didn't work though. It was recognized as a CNS (not CIE) and trying the test immediately stopped with an unable to initialize pin error. That's why I extrapolated what I needed and that was specific for the CIE.

@puccia About the CA: I was told by the Internal Ministry that the CIE was meant for signing and that they were considered automatically a CA. I work for an Italian municipality and we asked them specifically because some of the people that we have issued a CIE to has been asking us if this was possible.

Do you have an email where we might continue this privately? Are you Italian and do you prefer Italian?

**Comment by puccia** [comment]
Sure thing, ep [at] acm.org. Italian is my mother tongue, but feel free to pick Italian or English as is best for you :)

**Comment by dengert** [comment]
I would like this issue to remain open. Other users will run into the same issues:

  (1) There appears to be two different Italian ID cards, the CNS and the CIE?

  (2) OpenSC can not differentiate between some CardOS card with the CNS and a CIE card.

@wtmann @puccia  If the Italian government will only issue one of the other card to an individual is off topic,
but the issue of how OpenSC can tell the difference is not.

Removing the cardOS drivers is not a general solution. OpenSC should be smart enough to uniquely identify the
card and its application and use the correct drivers for the card and application without changes.
A way to tell them appear is needed even if this is to reorder the calling order of the drivers.
Do either of the older card CNS cards or newer CIE cards have an application ID, that can be tested?

An ATR in the historic bytes can contain a application ID of the default application for the card.
@wtmann it was not clear if you are an end user or a developer for the CIE cards.

In general the order should be drivers that can identify an application then drivers that try and identify
a card that does not use an application ID. (Other developers, please comment on this, this is a complex problem,
and we have many cards including older cards that may not even be used anymore.)


@wtmann You said in some note you made a copy of the card-iatcns.c and pkcs15-iatcns.c and renamed them for the CIE
but used OpenSC 0.13.0. This may be a solution for you, but not for others. Are you going to do the same for 0.15.0, and submit the changes?

Anyone else have experience with CIE cards?




On 8/18/2015 4:20 PM, wtmann wrote:
> Closed #521 <https://github.com/OpenSC/OpenSC/issues/521>.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/OpenSC/OpenSC/issues/521#event-385844013>.
>

-- 

  Douglas E. Engert  <DEEngert@gmail.com>

**Comment by dengert** [comment]
Comments please on the above.

**Comment by puccia** [comment]
@dengert 

Part of the problem is that the CNS and CIE specifications are rather generic, and leave quite some wiggle room for the implementation.

The filesystem specification prescribes a 2-byte ID, but not an AID. However they always have very specific historical bytes (see card-itacns.c:89 and following) that can be used for this purpose. If no problem can arise from there, I'd move itacns ahead of cardos in internal_card_drivers, if that's the right place.

As for the CNS vs. CIE problem, probably the right solution would be to provide a configuration option that allows us to set card->type correctly. (Now card->type defaults to CNS if a specific ATR is set to match in opensc.conf.)

I believe that some people did experiment successfully with CIE cards in the past!

**Comment by wtmann** [comment]
@dengert  I think the CIE driver probably works fine from version 2.0 and up; I think the real problem is that the version 1.1 of the CIE is different from the later ones. For example, in the historical bytes H8-H11 should contain ITID but on version 1 it doesn't. Also the file system is missing some items that are present in version 2 (such as the fingerprint and photo). I haven't been able to find any documentation at all regarding version 1 of the cards.

In this case I would be an end user for the card however I work for a municipality that issues them and am therefore in contact with the responsible ministry. I am a developer for the municipality but not for the CIE (the software I was writing is for internal use and I wanted to verify the possibility to sign documents with the CIE).

I did copy those two files and made some small changes, both on versions 0.13.0 and 0.15.0, and I can supply them to you (remember though that I haven't programmed in C for over 20 years so I can't say I understand completely how the values are being passed around). On the other hand, in the original code I did see some instances where they differentiated between versions 1 and 2 so I might be able to do some modifications to make the code better recognize a version 1 CIE than it actually does. Let me know what you'd prefer.

**Comment by puccia** [comment]
@wtmann, @dengert

Sorry for reading things incompletely earlier.

The proper fix could be to remove that ATR from card-cardos and add it to the static ATRs in card-itacns.

**Comment by dengert** [comment]
Sounds like you two should be working this out, and submitting patches. I am in the U.S. and have no interest in the cards, other then to make sure OpenSC works as expected.

**Comment by wtmann** [comment]
@puccia 

I already tried moving the ATR to the static ones in card-itacns but that didn't solve the problem. Somewhere in the code the card isn't being differentiated properly. Tomorrow I'll send you the two files I modified: maybe you'll see what the difference is.

**Comment by frankmorgner** [comment]
@wtmann did you and @puccia made any progress?

**Comment by frankmorgner** [comment]
so? what are the files you changed?
